name: memory_profiler
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  fake_async: ^1.3.3
  mason_logger: ^0.3.0
  memory_repository:
    path: packages/memory_repository
  pub_updater: ^0.5.0
  vm_service: ^15.0.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0

executables:
  memory_profiler:
