name: memory_repository
description: Repository encapsulating the logic for profiling memory using the Dart VM.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  vm_service: ^15.0.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
